title: Territoires de la Mémoire
email: robinfoguenne@territoires-memoire.be
description: >- # this means to ignore newlines until "baseurl:"
  L'asbl Les Territoires de la Mémoire est un centre d'Éducation à la Résistance et à la Citoyenneté.
#baseurl: "/nouveau2018" # the subpath of your site, e.g. /blog
url: "https://www.territoires-memoire.be" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  rbiiiii
lang: fr
timezone: Europe/Brussels

# Build settings
markdown: CommonMark
commonmark:
  options: ["SMART", "FOOTNOTES", "UNSAFE", "HARDBREAKS"]
  extensions: ["strikethrough", "autolink", "table"]
theme: minima

# Sass config
sass:
  style: compressed

# Server Config options
livereload: true     # You no longer need to include --livereload

# Global variablesjjekyll
assets_folder: assets
images_folder: assets/images

# Collections
collections:
  static-pages:
    title: Pages statiques
    output: true
    permalink: /:name/
  actualites:
    output: true
    permalink: /actualites/:year/:month/:title/
  focus:
    output: false
  agenda:
    output: true
    permalink: /agenda/:year/:month/:title/
  secondary-pages:
    output: true
    layout: secondary-page
  books:
    output: false
  aide-memoire-numeros:
    output: true
    permalink: /:title/
  aide-memoire:
    output: true
  communiques-presse:
    output: false
  tags:
    output: false
  enlien:
    output: true
    permalink: /en-lien/:title/
  emploi:
    output: true
    permalink: /emploi/:year/:month/:title/

# Default values for collections
defaults:
- scope:
    path: ''
    type: aide-memoire-numeros
  values:
    layout: am-num
- scope:
    path: ''
    type: aide-memoire
  values:
    layout: am-post


# Display posts with a future date
future: true

plugins:
 - jekyll-paginate-v2
 - jekyll-include-cache

# Pagination plugin config
pagination:
  enabled: true
  debug: false
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  trail: 
    before: 2
    after: 2

# Access-Control-Allow-Origin for custom fonts loading
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Includes    
include: ["_headers", "_redirects"]

# Excludes
exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/", ".forestry"]

lsi : false