[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/assets/*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "/assets/*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[build]
  functions = "functions" #  netlify-lambda reads this