[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "/assets/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/assets/json/*.geojson"
    [headers.values]
    Access-Control-Allow-Origin = "*"