---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: _actualites
  label: Actualites
  create: documents
  match: "**/*"
  templates:
  - actualites
- type: directory
  path: _agenda
  label: Agenda
  create: all
  match: "**/*"
- type: directory
  path: _aide-memoire-numeros
  label: Numéros Aide memoire
  create: all
  match: "**/*"
- type: directory
  path: _aide-memoire
  label: Articles Aide-mémoire
  create: all
  match: "**/*"
  templates:
  - articles-aide-memoire
- type: directory
  path: _books
  label: Livres BGO
  create: documents
  match: "**/*"
  templates:
  - livre-bgo
- type: directory
  path: _communiques-presse
  label: Communiques presse
  create: documents
  match: "**/*"
  templates:
  - communiques-de-presse
- type: directory
  path: _enlien
  label: Enlien
  create: documents
  match: "**/*"
  templates:
  - en-lien
- type: directory
  path: _focus
  label: Focus
  create: documents
  match: "**/*"
  templates:
  - focus
- type: directory
  path: _secondary-pages
  label: Pages secondaires
  create: all
  match: "**/*"
- type: directory
  path: _static-pages
  label: Pages principales
  create: all
  match: "**/*"
- type: directory
  path: en
  label: English
  create: documents
  match: "**/*"
upload_dir: assets/uploads
public_path: https://www.territoires-memoire.be/assets/uploads
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  - GIT_LFS_SKIP_SMUDGE=1
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
