---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: _actualites
  label: Actualités
  create: documents
  match: "**/*"
  templates:
  - actualites
- type: directory
  path: _agenda
  label: Agenda
  create: documents
  match: "**/*"
  templates:
  - evenement
- type: directory
  path: _focus
  label: Focus
  create: documents
  match: "**/*"
  templates:
  - focus
- type: directory
  path: _aide-memoire-numeros
  label: Numéros Aide memoire
  create: all
  match: "**/*"
- type: directory
  path: _aide-memoire
  label: Articles Aide-mémoire
  create: all
  match: "**/*"
  templates:
  - articles-aide-memoire
- type: directory
  path: _books
  label: Livres BGO
  create: documents
  match: "**/*"
  templates:
  - livre-bgo
- type: directory
  path: _static-pages
  label: Pages principales
  create: all
  match: "**/*"
- type: directory
  path: _secondary-pages
  label: Pages secondaires
  create: all
  match: "**/*"
- type: directory
  path: _communiques-presse
  label: Communiqués de presse
  create: documents
  match: "**/*"
  templates:
  - communiques-de-presse
- type: document
  path: _data/permanents.yml
  label: Permanents
- type: document
  path: _data/editions.yml
  label: Livres de la page éditions
- type: document
  path: _data/cdl.yml
  label: Citoyens du Livre
- type: document
  path: _data/pdf_items.yml
  label: Documents pdf
- type: document
  path: _data/pdf_txt_items.json
  label: Documents pdf avec description et +
- type: directory
  path: _enlien
  label: En lien
  create: documents
  match: "**/*"
  templates:
  - en-lien
- type: directory
  path: en
  label: English
  create: documents
  match: "**/*"
- type: directory
  path: nl
  label: Nederlands
  create: documents
  match: "**/*"
- type: directory
  path: de
  label: Deutsch
  create: documents
  match: "**/*"
upload_dir: assets/uploads
public_path: "/assets/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  - GIT_LFS_SKIP_SMUDGE=1
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
