---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: _actualites
  label: Actualites
  create: all
  match: "**/*"
- type: directory
  path: _agenda
  label: Agenda
  create: all
  match: "**/*"
- type: directory
  path: _aide-memoire
  label: Aide memoire
  create: all
  match: "**/*"
- type: directory
  path: _am-posts
  label: Am posts
  create: all
  match: "**/*"
- type: directory
  path: _books
  label: Books
  create: documents
  match: "**/*"
- type: directory
  path: _communiques-presse
  label: Communiques presse
  create: all
  match: "**/*"
- type: directory
  path: _enlien
  label: Enlien
  create: all
  match: "**/*"
- type: directory
  path: _focus
  label: Focus
  create: all
  match: "**/*"
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: _secondary-pages
  label: Secondary pages
  create: all
  match: "**/*"
- type: directory
  path: _static-pages
  label: Static pages
  create: all
  match: "**/*"
upload_dir: assets/uploads
public_path: https://www.territoires-memoire.be/assets/uploads
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
instant_preview: 
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  publish_command: bundle exec jekyll build -d _site
  publish_env:
  - JEKYLL_ENV=production
  output_directory: _site
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
